### ISSUE TITLE
load no symfony

### ISSUE THREAD

**Issue by rom232** [eNotasGW/php-client#1]
Olá @jonathansouza, boa noite.

Gostaria de saber se tem algum meio especifico de fazer o autoload funcionar com o Symfony 3.3.6

Obrigado,

**Comment by otavioreis** [comment]
Boa tarde Rom232, tudo bem?
  
  Infelizmente nós não controlávamos as perguntas que nos eram encaminhadas aqui no GitHub, mas agora estamos mais atentos para não deixar nossos clientes sem respostas, seja qual for a plataforma. Acredito que como a sua pergunta possui mais de um ano, você já deve ter resolvido esta questão, correto?

Atenciosamente,
Otávio A. Reis

**Comment by otavioreis** [comment]
@rom232 eu irei fechar este problema, mas se precisar basta reabrir.

Atenciosamente,
Otávio A. Reis
