### ISSUE TITLE
Composer?

### ISSUE THREAD

**Issue by gabrielkoerich** [eNotasGW/php-client#3]
Algum motivo para não utilizarem Composer?

Não é certo eu ter que baixar um zip do projeto e adicionar todo o código no meu repositório.

O melhor seria que vocês adicionassem o repositório no [packagist](https://packagist.org) e trabalhassem com [semantic versioning](https://semver.org).

Abs

**Comment by otavioreis** [comment]
Boa tarde Gabriel, tudo bem?

  No momento não temos planos para adicionar o código ao Composer, mas pode ser que no futuro venhamos a fazer isso.

Atenciosamente,
Otávio A. Reis
